Add report URL for IONOS.  No email address to send phishing to tho
fleaz/report-phishing pull request #1
Opened 2023-02-15 21:24 UTC by thexhr

2023-02-15 21:45 UTC, fleaz requested changes

2023-02-15 21:45 UTC, fleaz commented on data.yaml
> +  address: "--"
Can you please change this to `address: ""` then it gets ignored by the script and we wont generate an link with `mailto:--`

2023-02-16 07:01 UTC, thexhr commented on data.yaml
> +  address: "--"
Sure, done

2023-02-16 09:39 UTC, merged

2023-02-16 09:40 UTC, fleaz commented
Thank you for contributing 🎉